# -*- coding: utf-8 -*-
"""server.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bagCfdP0TFBlL3innat9Cy3ilODfxzbA
"""

import keras
from flask import Flask, jsonify, request
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Embedding, LSTM
from keras.callbacks import EarlyStopping
import pandas as pd
import joblib
from keras.models import model_from_json
import json
from json import JSONEncoder
import numpy as np

app = Flask(__name__)

class NumpyArrayEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        elif isinstance(obj, np.floating):
            return float(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        else:
            return super(NumpyArrayEncoder, self).default(obj)

@app.route("/predict", methods=['POST'])
def do_prediction():
    json1 = request.get_json()
    json_file = open('model.json', 'r')
    loaded_model_json = json_file.read()
    json_file.close()
    model = model_from_json(loaded_model_json)
# load weights into new model
    model.load_weights("model.h5")
    df = pd.DataFrame(json1, index=[0])
    max_features = 2000
    tokenizer = Tokenizer(num_words=max_features, split=' ')
    data=df["filteredCleanedText"].values.tolist()
    tokenizer.fit_on_texts(data)
    X = tokenizer.texts_to_sequences(data)
    X = pad_sequences(X)
    y_predict=model.predict(X)
    if y_predict[0] < 0.5:
        y_predict[0]=0
    else:
        y_predict[0]=1
    result = {"Prediction" : y_predict[0]}
    encodedNumpyData = json.dumps(result, cls=NumpyArrayEncoder)
    return encodedNumpyData

if __name__ == "__main__":
    app.run(host='0.0.0.0')
